name: Deploiement en continu

on:
  push:
    branches: [ master ]

jobs:  
  version:    
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:      
      - uses: actions/checkout@v2
        with:          
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name '${{ secrets.maxbtchr }}'  
      - run: git config --global user.email '${{ secrets.maxboucher.web@gmail.com }}'      
      - run: npm version patch -m "[RELEASE] %s"      
      - run: git push