name: Deploiement en continu

on:
  push:
    branches: [ master ]

jobs:  
  version:    
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:      
      - uses: actions/checkout@v2
        with:          
          token: ${{ secrets.SECRET_ACCESS_TOKEN }}
      - run: git config --global user.name '${{ secrets.GH_PUBLIC_NAME }}'  
      - run: git config --global user.email '${{ secrets.GH_EMAIL }}'      
      - run: npm version patch -m "[RELEASE] %s"      
      - run: git push
      - run: git tag 1.0.0
      - run: git push --tags
  web-deploy:
    name: Deploiement FTP
    runs-on: ubuntu-latest
    steps:
      - name: Deployer derniere version du code
        uses: actions/checkout@v2
      
      - name: Synchroniser fichiers
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_COMPONENTS_ACCESS_TOKEN }}